#!/bin/bash

# uninstall first in case this is an upgrade
/data/data/com.termux/files/usr/local/bin/cloudflared service uninstall

# install the new service using launchctl
/data/data/com.termux/files/usr/local/bin/cloudflared service install